### ISSUE TITLE
Github webhook gives 301 error 

### ISSUE THREAD

**Issue by mayarichman** [noelboss/deepl.io#4]
I've changed the config.json to have a special token and added all the files from the repo to deploy.domain.org. The index page says the mod_rewrite and .htaccess are working and `config.json: Found and well formated`.

I added the webhook url as http://deploy.domain.org/token but I keep getting a 301 with nothing the body and metadata:

`
Connection: close
Content-length: 0
Location: https://deploy.domain.org/token/
`

Is the problem that it is trying to access https which isn't working? There are no logs in the logs folder either.

I am also not sure if my repositoriesPath variable is correct. Could that be the reason for the payload failure?

Thanks!

**Comment by mayarichman** [comment]
Ok, I had a problem because of the SSL cert, but I got that fixed. The webhook isn't working for the url with the token though, it says that the page doesn't exist. Do I have to do anything other than add the token to the config.json?

**Comment by natronite** [comment]
Only recently started using deepl.io but I did have the same problem. It turns out most errors in the script return a '404 NOT FOUND' (applies to version 0.9.0). This can have several causes (list non-exhaustive):

- repository_ssh_url is wrong
- branch does not match
- error in branch.script.sh
- security token mismatch
- IP not allowed

Did u check the logs/deeplio.log for more information? If the file does not exist php might not have permission to write to it (same for cache directory).

**Comment by noelboss** [comment]
thanks @natronite for your comment…

**Comment by natronite** [comment]
As we say in Switzerland. Gärn gscheh!
